feat(product-grid): compact mode
FranckG28/Vine pull request #33
Opened 2023-09-19 12:41 UTC by FranckG28

Closes #32

2023-09-19 12:47 UTC, jvondermarck requested changes
To medidate... 
![npc](https://github.com/FranckG28/Vine/assets/62793491/289a5c5e-1dff-47e2-8ed5-307679b7023f)

2023-09-19 14:08 UTC, FranckG28 commented on components/shared/toggle.tsx
> +    icon1: JSX.Element,
it's not possible since each icons are a separate component. I can't get one by their name :(

2023-09-19 14:10 UTC, FranckG28 commented on components/home/product-view.tsx
> +        pageSize: compactMode ? 100 : 48
Fixed ;)

2023-09-19 14:11 UTC, jvondermarck commented on components/shared/toggle.tsx
> +    icon1: JSX.Element,
ohh valeee

2023-09-20 06:22 UTC, ErenMustafaGit requested changes
🍔

2023-09-20 06:22 UTC, ErenMustafaGit commented on components/home/card.tsx
> +        <Tooltip content={tooltip}>
z-index for the tooltip, the right card hide the tooltip :
![image](https://github.com/FranckG28/Vine/assets/82711747/fafeb5a9-4127-4bc1-80ca-11e5102f165e)

2023-09-20 06:22 UTC, ErenMustafaGit commented on components/home/product-view.tsx
> +          <div className="max-lg:hidden">
Why the compact mode must be hidden for small screen ? 
The feature would be cool for mobile users (they have only 1 product by 1)

Maybe the mobile compact mode must show 2 or 3 columns ?

2023-09-20 06:22 UTC, ErenMustafaGit commented on components/home/product-view.tsx
> +              onToggle={(val) => {
Store the value in localstorage with usehooks-ts 😄 
We loose our choice when refreshing the page 😢

2023-09-20 06:22 UTC, ErenMustafaGit commented on components/shared/switch.tsx
> +      <div className="z-10 p-2">{icon1}</div>
Beautiful component 😍 
But can we have a lighter color for icons and a hover state ?

2023-09-22 08:23 UTC, FranckG28 commented on components/home/card.tsx
> +        <Tooltip content={tooltip}>
Good catch !

2023-09-22 08:33 UTC, FranckG28 commented on components/home/product-view.tsx
> +              onToggle={(val) => {
✋✋✋✋✋✋

2023-09-22 08:33 UTC, FranckG28 commented on components/shared/switch.tsx
> +      <div className="z-10 p-2">{icon1}</div>
Maybe 🫠

2023-09-22 08:43 UTC, FranckG28 commented on components/home/product-view.tsx
> +          <div className="max-lg:hidden">
![image](https://github.com/FranckG28/Vine/assets/19238963/f0d6e49e-037f-43e2-b6b6-bd3823fc3202)
Ok not bad

2023-09-22 08:58 UTC, FranckG28 commented on components/home/product-view.tsx
> +              onToggle={(val) => {
Done ;) I had to do a little trick to allow the value of the localStorage of the client to be different from the server one (always false since there is no localstorage on server). See in switch component

2023-09-22 12:13 UTC, ErenMustafaGit requested changes
Product name not appearing : seems to be md screen ? 
![image](https://github.com/FranckG28/Vine/assets/82711747/a07f04f0-1fb1-4471-8fb8-25793e72d028)
![image](https://github.com/FranckG28/Vine/assets/82711747/ce0dafa9-e508-4cd6-9157-efaa5710a681)

2023-09-23 10:45 UTC, FranckG28 commented
> Product name not appearing : seems to be md screen ? ![image](https://user-images.githubusercontent.com/82711747/269932514-a07f04f0-1fb1-4471-8fb8-25793e72d028.png) ![image](https://user-images.githubusercontent.com/82711747/269932778-ce0dafa9-e508-4cd6-9157-efaa5710a681.png)

Fixed, thanks ;)

2023-09-23 10:59 UTC, ErenMustafaGit requested changes
Small UI issue : 
![image](https://github.com/FranckG28/Vine/assets/82711747/544759eb-6f40-40aa-9df5-b3d3e42773b0)

2023-09-23 10:59 UTC, ErenMustafaGit commented on components/home/products-grid.tsx
> +                  tooltip={product.attributes.title}
⚠️ Unseen Badge BUG NOT WORKING
IntersectionObserverWrapper need an id on his children, i know it was not the best option to do it...

in this wrapper : 
```
refedChildren.props?.id
```

Maybe give the id to UnseenBadge and then to IntersectionObserverWrapper

2023-09-23 14:39 UTC, FranckG28 commented
> Small UI issue : ![image](https://user-images.githubusercontent.com/82711747/270102985-544759eb-6f40-40aa-9df5-b3d3e42773b0.png)

UI issue fixed ;)

![image](https://github.com/FranckG28/Vine/assets/19238963/546fb8e3-20e3-4250-94e5-f35c46c614b0)

2023-09-23 14:50 UTC, FranckG28 commented on components/home/products-grid.tsx
> +                  tooltip={product.attributes.title}
Fixed !!

2023-09-23 14:54 UTC, ErenMustafaGit approved these changes
AMAZING 😍

2023-09-23 14:59 UTC, merged